name: CI workflow

on:
  push:
    branches: [ "dev" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0.308

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Frontend
        run: dotnet restore src/AestraliaFrontend/AestraliaFrontend.csproj

      - name: Build Frontend
        run: dotnet build src/AestraliaFrontend/AestraliaFrontend.csproj --configuration Release --no-restore

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: src/AestraliaFrontend/bin/Release

  build-backend:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0.308

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Backend
        run: dotnet restore src/AestraliaBackend/AestraliaBackend.csproj

      - name: Build Backend
        run: dotnet build src/AestraliaBackend/AestraliaBackend.csproj --configuration Release --no-restore

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: src/AestraliaBackend/bin/Release

  test:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0.308

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./build/frontend

      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: ./build/backend

      - name: Run Frontend Tests
        run: dotnet test src/AestraliaFrontend/AestraliaFrontend.csproj --configuration Release --verbosity normal

      - name: Run Backend Tests
        run: dotnet test src/AestraliaBackend/AestraliaBackend.csproj --configuration Release --verbosity normal